name: ktx_viewer
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.3.0

dependencies:
  thermion_dart: 
    # git:
    #   url: https://github.com/nmfisher/thermion.git
    #   path: thermion_dart
    path: /Users/nickfisher/Documents/thermion/thermion_dart
  logging: ^1.3.0
  web: ^1.1.1

# dependency_overrides: 
#   thermion_dart:
#     path: /Users/nickfisher/Documents/thermion/thermion_dart

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.15
  build_test: ^2.2.2
  build_web_compilers: ^4.1.5
